
networks:
  default:
    driver: bridge

services:
#  ollama:
#    image: ollama/ollama
#    container_name: ollama
#    pull_policy: always
#    ports:
#      - "11434:11434"
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - default
    environment:
      QDRANT__GPU__INDEXING: 1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: 1
    volumes:
      - ./qdrant/data:/qdrant/storage
      - ./qdrant/config/production.yaml:/qdrant/config/production.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq
#    ports:
#      - '5672:5672'
#      - '15672:15672'
#    networks:
#      - default
#    environment:
#      - RABBITMQ_SECURE_PASSWORD=yes
#      - RABBITMQ_DEFAULT_USER=tuan
#      - RABBITMQ_DEFAULT_PASS=20226100
#      - RABBITMQ_DEFAULT_VHOST=/
#    volumes:
#      - ./rabbitmq/plugin:/etc/rabbitmq
#      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/







